title: Eduardo Torres Davila
url: "https://etdavila10.github.io"
baseurl: ""

ins_logo: "assets/images/umn_logo.png"

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://github.com/etdavila10/etdavila10.github.io"
footer_text: "Built by Eduardo Torres Davila"

sass:
  style: compressed
  sass_dir: _sass

nav:
  - name: "About"
    link: "/"
  - name: "CV"
    link: "assets/documents/cv.pdf"
  - name: "Research"
    link: "research"
  - name: "Projects"
    link: "projects"
  - name: "Teaching"
    link: "teaching"
  - name: "Contact"
    link: "contact"

car_images:
  - name: "Freddy"
    caption: "my dog"
    link: "assets/images/freddy.png"
  - name: "Motorcycle"
    caption: "When I used to ride motorcycles"
    link: "assets/images/moto.png"
  - name: "Keyboards"
    caption: "I am really into keyboards"
    link: "assets/images/keebs.png"
  - name: "Camping"
    caption: "First time I went winter camping"
    link: "assets/images/camp.png"
  - name: "Golden Gate"
    caption: "Of course, I am from the bay area"
    link: "assets/images/golden_gate.png"
  - name: "mexico"
    caption: "Best tamales and atole ever"
    link: "assets/images/atole.png"